import math as m
#maths functions
num=int(input("enter the number"))
power=int(input("enter the power value"))
print("celi",m.ceil(num))
print("sqrt",m.sqrt(num))
print("exp",m.exp(num))
print("fabs",m.fabs(num))
print("floor",m.floor(num))
print("log with base",m.log(num))
print("log10",m.log10(num))
print("pow",m.pow(num,power))
print("sin",m.sin(num))
print("cos",m.cos(num))
print("tan",m.tan(num))
print("degrees",m.degrees(num))
print("radian",m.radians(num))
